# Generated by Django 5.2 on 2025-05-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'subject', 'term')},
        ),
    ]
